export default function(env) {
  return {
    /**
		 * 自定义语法
		 */
    // 支持 postcss-scss postcss-less postcss-html postcss-lit
    customSyntax: 'postcss-less', 
    extends: [
      'stylelint-config-standard',
      'stylelint-config-css-modules',
      'stylelint-config-recommended-less',
      /* Vue */
      env === 'vue' && 'stylelint-config-html/html',
      env === 'vue' && 'stylelint-config-html/vue'
    ].filter(Boolean),
    plugins: [
      'stylelint-order',
      'stylelint-declaration-block-no-ignored-properties'
    ],
    rules: {
      /* 指定声明块内的内容顺序 */
      'order/order': [
        // less变量
        'at-variables',
        // sass变量
        'dollar-variables', 
        // css变量
        'custom-properties', 
        // css声明块, (display: block)
        'declarations', 
        // 嵌套规则, (a { span {} })
        'rules', 
        // 嵌套'@'规则, (div { @media () {} })
        'at-rules'
      ],
      /* 指定声明块中的属性顺序 */
      'order/properties-order': [
        'position',
        'z-index',
        'top',
        'bottom',
        'left',
        'right',
        'float',
        'clear',
        'columns',
        'columns-width',
        'columns-count',
        'column-rule',
        'column-rule-width',
        'column-rule-style',
        'column-rule-color',
        'column-fill',
        'column-span',
        'column-gap',
        'display',
        'grid',
        'grid-template-rows',
        'grid-template-columns',
        'grid-template-areas',
        'grid-auto-rows',
        'grid-auto-columns',
        'grid-auto-flow',
        'grid-column-gap',
        'grid-row-gap',
        'grid-template',
        'grid-template-rows',
        'grid-template-columns',
        'grid-template-areas',
        'grid-gap',
        'grid-row-gap',
        'grid-column-gap',
        'grid-area',
        'grid-row-start',
        'grid-row-end',
        'grid-column-start',
        'grid-column-end',
        'grid-column',
        'grid-column-start',
        'grid-column-end',
        'grid-row',
        'grid-row-start',
        'grid-row-end',
        'flex',
        'flex-grow',
        'flex-shrink',
        'flex-basis',
        'flex-flow',
        'flex-direction',
        'flex-wrap',
        'justify-content',
        'align-content',
        'align-items',
        'align-self',
        'order',
        'table-layout',
        'empty-cells',
        'caption-side',
        'border-collapse',
        'border-spacing',
        'list-style',
        'list-style-type',
        'list-style-position',
        'list-style-image',
        'ruby-align',
        'ruby-merge',
        'ruby-position',
        'box-sizing',
        'width',
        'min-width',
        'max-width',
        'height',
        'min-height',
        'max-height',
        'padding',
        'padding-top',
        'padding-right',
        'padding-bottom',
        'padding-left',
        'margin',
        'margin-top',
        'margin-right',
        'margin-bottom',
        'margin-left',
        'border',
        'border-width',
        'border-top-width',
        'border-right-width',
        'border-bottom-width',
        'border-left-width',
        'border-style',
        'border-top-style',
        'border-right-style',
        'border-bottom-style',
        'border-left-style',
        'border-color',
        'border-top-color',
        'border-right-color',
        'border-bottom-color',
        'border-left-color',
        'border-image',
        'border-image-source',
        'border-image-slice',
        'border-image-width',
        'border-image-outset',
        'border-image-repeat',
        'border-top',
        'border-top-width',
        'border-top-style',
        'border-top-color',
        'border-top',
        'border-right-width',
        'border-right-style',
        'border-right-color',
        'border-bottom',
        'border-bottom-width',
        'border-bottom-style',
        'border-bottom-color',
        'border-left',
        'border-left-width',
        'border-left-style',
        'border-left-color',
        'border-radius',
        'border-top-right-radius',
        'border-bottom-right-radius',
        'border-bottom-left-radius',
        'border-top-left-radius',
        'outline',
        'outline-width',
        'outline-color',
        'outline-style',
        'outline-offset',
        'overflow',
        'overflow-x',
        'overflow-y',
        'resize',
        'visibility',
        'font',
        'font-style',
        'font-variant',
        'font-weight',
        'font-stretch',
        'font-size',
        'font-family',
        'font-synthesis',
        'font-size-adjust',
        'font-kerning',
        'line-height',
        'text-align',
        'text-align-last',
        'vertical-align',
        'text-overflow',
        'text-justify',
        'text-transform',
        'text-indent',
        'text-emphasis',
        'text-emphasis-style',
        'text-emphasis-color',
        'text-emphasis-position',
        'text-decoration',
        'text-decoration-color',
        'text-decoration-style',
        'text-decoration-line',
        'text-underline-position',
        'text-shadow',
        'white-space',
        'overflow-wrap',
        'word-wrap',
        'word-break',
        'line-break',
        'hyphens',
        'letter-spacing',
        'word-spacing',
        'quotes',
        'tab-size',
        'orphans',
        'writing-mode',
        'text-combine-upright',
        'unicode-bidi',
        'text-orientation',
        'direction',
        'text-rendering',
        'font-feature-settings',
        'font-language-override',
        'image-rendering',
        'image-orientation',
        'image-resolution',
        'shape-image-threshold',
        'shape-outside',
        'shape-margin',
        'color',
        'background',
        'background-image',
        'background-position',
        'background-size',
        'background-repeat',
        'background-origin',
        'background-clip',
        'background-attachment',
        'background-color',
        'background-blend-mode',
        'isolation',
        'clip-path',
        'mask',
        'mask-image',
        'mask-mode',
        'mask-position',
        'mask-size',
        'mask-repeat',
        'mask-origin',
        'mask-clip',
        'mask-composite',
        'mask-type',
        'filter',
        'box-shadow',
        'opacity',
        'transform-style',
        'transform',
        'transform-box',
        'transform-origin',
        'perspective',
        'perspective-origin',
        'backface-visibility',
        'transition',
        'transition-property',
        'transition-duration',
        'transition-timing-function',
        'transition-delay',
        'animation',
        'animation-name',
        'animation-duration',
        'animation-timing-function',
        'animation-delay',
        'animation-iteration-count',
        'animation-direction',
        'animation-fill-mode',
        'animation-play-state',
        'scroll-behavior',
        'scroll-snap-type',
        'scroll-snap-destination',
        'scroll-snap-coordinate',
        'cursor',
        'touch-action',
        'caret-color',
        'ime-mode',
        'object-fit',
        'object-position',
        'content',
        'counter-reset',
        'counter-increment',
        'will-change',
        'pointer-events',
        'all',
        'page-break-before',
        'page-break-after',
        'page-break-inside',
        'widows'
      ],
      // 禁止无效的 16 进制颜色
      'color-no-invalid-hex': true, 
      // 禁止字体名称重复
      'font-family-no-duplicate-names': true, 
      // 禁止字体缺失字体系列关键字
      'font-family-no-missing-generic-family-keyword': true, 
      // 禁止在 calc 函数中使用没有间隔的运算符
      'function-calc-no-unspaced-operator': true, 
      // 禁止字符串中出现换行符
      'string-no-newline': true, 
      // 禁止使用未知单位
      'unit-no-unknown': [true, { ignoreUnits: ['rpx'] }], 
      // 禁止使用未知属性
      'property-no-unknown': [true, { ignoreProperties: ['composes'] }],
      // 禁止在同一个声明块中出现重复的属性
      'declaration-block-no-duplicate-properties': [true],
      // 禁止使用无效的 ID 选择器
      'selector-id-pattern': '^[a-z][a-zA-Z0-9]+$', 
      // 禁止使用无效的 class 选择器
      'selector-class-pattern': '^[a-z][a-zA-Z0-9]+$|^ant-|^antd-|^anticon-|^amap-|^echarts-|^icon-|^icons-|^slick-|^swiper-', 
      // 禁止使用未知的伪类选择器
      'selector-pseudo-class-no-unknown': [true, { ignorePseudoClasses: ['global'] }],
      // 禁止使用未知的伪元素选择器
      'selector-pseudo-element-no-unknown': true, 
      // 禁止使用未知的选择器类型
      'selector-type-no-unknown': null,           
      // 禁止使用非全小写的伪类选择器
      'selector-pseudo-class-case': 'lower', 
      // 指定类型选择器的大小写
      'selector-type-case': 'lower', 
      // 禁止使用未知的媒体特性
      'media-feature-name-no-unknown': true, 
      // 禁止使用未知的@规则
      'at-rule-no-unknown': true, 
      // 禁止空注释
      'comment-no-empty': true, 
      // 禁止重复 @import
      'no-duplicate-at-import-rules': true, 
      // 禁止重复的选择器
      'no-duplicate-selectors': true, 
      // 禁止空源码
      'no-empty-source': null, 
      // 禁止额外的分号
      'no-extra-semicolons': true, 
      // 强制使用单引号
      'string-quotes': 'single', 
      // 强制属性名称使用小写
      'property-case': 'lower', 
      // 禁止行尾空白符
      'no-eol-whitespace': true, 
      // 强制函数名称使用小写
      'function-name-case': 'lower', 
      // 缩进
      'indentation': 2, 
      // 禁止数字前面的 0
      'number-leading-zero': 'never', 
      // 禁止数字末尾的 0
      'number-no-trailing-zeros': true, 
      // 禁止长度为 0 的单位
      'length-zero-no-unit': true, 
      // 强制属性冒号后有空格
      'declaration-colon-space-after': 'always', 
      // 限制相邻空行的数量
      'max-empty-lines': 1, 
      // 限制值列表中相邻空行的数量
      'value-list-max-empty-lines': 0, 
      // 禁止简写属性中的重复值
      'shorthand-property-no-redundant-values': true, 
      // 禁止可合并为一个简写属性的扩写属性
      'declaration-block-no-redundant-longhand-properties': true, 
      // 要求在声明块的分号之后必须有换行符或不能有空白符
      'declaration-block-semicolon-newline-after': 'always', 
      // 要求在块的闭大括号之后必须有换行符或不能有空白符
      'block-closing-brace-newline-after': 'always', 
      // 要求在媒体功能的冒号之后必须有一个空格或不能有空白符
      'media-feature-colon-space-after': 'always', 
      // 要求在媒体功能的范围运算符之后必须有一个空格或不能有空白符
      'media-feature-range-operator-space-after': 'always', 
      // 要求在@规则名之后必须有一个空格
      'at-rule-name-space-after': 'always', 
      // 要求在声明块的冒号之后必须有换行符或不能有空白符
      'declaration-colon-newline-after': null, 
      // 禁止属性的浏览器引擎前缀
      'property-no-vendor-prefix': null, 
      // 禁止空块
      'block-no-empty': null, 
      // 禁止在具有较高优先级的选择器后出现被其覆盖的较低优先级的选择器
      'no-descending-specificity': null, 
      // 强制使用数字表示透明度
      'alpha-value-notation': 'number', 
      // 为适用的颜色函数指定现代或传统表示法
      'color-function-notation': null, 
      // 禁止使用未知的函数
      'function-no-unknown': [true, { ignoreFunctions: ['constant'] }],
      'plugin/declaration-block-no-ignored-properties': true,
      // 强制使用引号括起URL
      'function-url-quotes': 'always', 
      // 强制使用引号括起属性选择器
      'selector-attribute-quotes': 'always', 
      'value-keyword-case': ['lower', { ignoreProperties: ['composes'] }],
      // 强制单位使用小写
      'unit-case': null,                  
      'value-no-vendor-prefix': null
    }
  };
}